### ISSUE TITLE
How to build static pages?

### ISSUE THREAD

**Issue by suchov** [Ruby-School/ruby-school.github.io#1]
guys, how do you think - should we fork NodeSchool static pages or create our own one, maybe [Jekyll](https://jekyllrb.com/) ?

**Comment by flor-master** [comment]
I think we can create our own site on Jekyll or another static site generators, based on node.js, like http://wintersmith.io or http://www.metalsmith.io

**Comment by flor-master** [comment]
I think we can create our own site on Jekyll or another static site generators, based on node.js, like http://wintersmith.io or http://www.metalsmith.io

**Comment by flor-master** [comment]
I think we can create our own site on Jekyll or another static site generators, based on node.js, like http://wintersmith.io or http://www.metalsmith.io

**Comment by flor-master** [comment]
I think we can create our own site on Jekyll or another static site generators, based on node.js, like http://wintersmith.io or http://www.metalsmith.io

**Comment by suchov** [comment]
Jekyll sounds more appropriate cause it's based on Ruby.

**Comment by flor-master** [comment]
I was try Jekyll, it look nice). We can try it. For custom parts we will develop custom gem.

**Comment by suchov** [comment]
exactly, sorry I added couple commits to master, but in those commits are Jekyll and index.html with not working title, but we can start from there
To run the project - just clone it and run "jekyll serve -w"
