### ISSUE TITLE
Need a Logo & favicon

### ISSUE THREAD

**Issue by suchov** [Ruby-School/ruby-school.github.io#2]
I think it should be something similar to [nodejs logo](https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTqluvv281JVfGZ4-gZp6laeDYtvJRG_deXOXI4ec1-nYqXASE7si15eA)

**Comment by flor-master** [comment]
Hi, I created PR for Logo and favicons. 
https://github.com/Ruby-School/ruby-school.github.io/pull/8

It contains a simple ruby-shaped logo, simple favicons, and a new structure of public files.

**Comment by suchov** [comment]
#8
